<a href="https://colab.research.google.com/github/Taryn-Cail/Predicting-Dementia-Diagnosis-Using-Lifestyle-and-Health-Factors/blob/main/CS4403_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predicting Dementia Diagnosis Using Lifestyle and Health Factors

CS4403 Project Data Cleaning and Preprocessing
Taryn Cail - 3756155



# Data Cleaning and Preprocessing

## Importing Data

In [ ]:
#imports for processing the data
import pandas as pd
import numpy as np
import glob
from google.colab import drive
from google.colab import data_table
data_table.enable_dataframe_formatter()

In [ ]:
#upload csv files from google drive
drive.mount('/content/drive')
df1 = pd.read_csv('/content/drive/MyDrive/data/alzheimers_disease_data.csv')
df2 = pd.read_csv('/content/drive/MyDrive/data/dementia_patients_health_data.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


df1 = alzheimers_disease_data.csv

df2 = dementia_patients_health_data.csv

##Original Information

In [ ]:
# print all the data frames to compare and contrast information
df1.info()

df2.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 35 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   PatientID                  2149 non-null   int64  
 1   Age                        2149 non-null   int64  
 2   Gender                     2149 non-null   int64  
 3   Ethnicity                  2149 non-null   int64  
 4   EducationLevel             2149 non-null   int64  
 5   BMI                        2149 non-null   float64
 6   Smoking                    2149 non-null   int64  
 7   AlcoholConsumption         2149 non-null   float64
 8   PhysicalActivity           2149 non-null   float64
 9   DietQuality                2149 non-null   float64
 10  SleepQuality               2149 non-null   float64
 11  FamilyHistoryAlzheimers    2149 non-null   int64  
 12  CardiovascularDisease      2149 non-null   int64  
 13  Diabetes                   2149 non-null   int64

##Removing Columns

In [ ]:
# keeping these columns from df1
keep_cols_df1 = [
 'Age',
 'Gender',
 'EducationLevel',
 'Smoking',
 'AlcoholConsumption',
 'PhysicalActivity',
 'DietQuality',
 'SleepQuality',
 'FamilyHistoryAlzheimers',
 'CardiovascularDisease',
 'Diabetes',
 'Depression',
 'Hypertension',
 'Diagnosis'
]


In [ ]:
#keeping only these columns from df1
df1 = df1[keep_cols_df1]


In [ ]:
df1.columns.tolist()
df1.head()


,Age,Gender,EducationLevel,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,FamilyHistoryAlzheimers,CardiovascularDisease,Diabetes,Depression,Hypertension,Diagnosis
0,73,0,2,0,13.297218,6.327112,1.347214,9.025679,0,0,1,1,0,0
1,89,0,0,0,4.542524,7.619885,0.518767,7.151293,0,0,0,0,0,0
2,73,0,1,0,19.555085,7.844988,1.826335,9.673574,1,0,0,0,0,0
3,74,1,1,1,12.209266,8.428001,7.435604,8.392554,0,0,0,0,0,0
4,89,0,0,0,18.454356,6.310461,0.795498,5.597238,0,0,0,0,0,0


In [ ]:
#Keep these columns for df2
keep_cols_df2 = [
    'Diabetic',
    'AlcoholLevel',
    'Age',
    'Education_Level',
    'Gender',
    'Family_History',
    'Smoking_Status',
    'Physical_Activity',
    'Depression_Status',
    'Nutrition_Diet',
    'Sleep_Quality',
    'Chronic_Health_Conditions',
    'Dementia'
]

In [ ]:
df2 = df2[keep_cols_df2]

In [ ]:
df2.columns.tolist()
df2.head()

,Diabetic,AlcoholLevel,Age,Education_Level,Gender,Family_History,Smoking_Status,Physical_Activity,Depression_Status,Nutrition_Diet,Sleep_Quality,Chronic_Health_Conditions,Dementia
0,1,0.084974,60,Primary School,Female,No,Current Smoker,Sedentary,No,Low-Carb Diet,Poor,Diabetes,0
1,0,0.016973,61,Secondary School,Male,No,Former Smoker,Moderate Activity,No,Low-Carb Diet,Poor,Heart Disease,1
2,0,0.009000,69,Primary School,Male,Yes,Former Smoker,Moderate Activity,No,Mediterranean Diet,Poor,Heart Disease,0
3,0,0.086437,78,Secondary School,Female,Yes,Never Smoked,Mild Activity,Yes,Balanced Diet,Poor,Hypertension,1
4,1,0.150747,77,Secondary School,Male,Yes,Never Smoked,Mild Activity,No,Low-Carb Diet,Good,Diabetes,1


##Altering Chronic Disease Column

manipulating chronic disease column in df2 to have three seperate columns for heart disease, diabetes and hypertension,ignoring any other conditions


In [ ]:
#going through the chronic health conditions column and seperating it
#ASSUMING that NAN values are 0
df2['Chronic_Diabetes'] = df2['Chronic_Health_Conditions'].str.contains('Diabetes', case=False, na=False).astype(int)

df2['Hypertension'] = df2['Chronic_Health_Conditions'].str.contains('Hypertension', case=False, na=False).astype(int)

df2['CardiovascularDisease'] = df2['Chronic_Health_Conditions'].str.contains('Heart', case=False, na=False).astype(int)


In [ ]:
# dropping health conditions column
df2 = df2.drop(columns=['Chronic_Health_Conditions'])


In [ ]:
#displaying new dataset 2
df2.head()

,Diabetic,AlcoholLevel,Age,Education_Level,Gender,Family_History,Smoking_Status,Physical_Activity,Depression_Status,Nutrition_Diet,Sleep_Quality,Dementia,Chronic_Diabetes,Hypertension,CardiovascularDisease
0,1,0.084974,60,Primary School,Female,No,Current Smoker,Sedentary,No,Low-Carb Diet,Poor,0,1,0,0
1,0,0.016973,61,Secondary School,Male,No,Former Smoker,Moderate Activity,No,Low-Carb Diet,Poor,1,0,0,1
2,0,0.009000,69,Primary School,Male,Yes,Former Smoker,Moderate Activity,No,Mediterranean Diet,Poor,0,0,0,1
3,0,0.086437,78,Secondary School,Female,Yes,Never Smoked,Mild Activity,Yes,Balanced Diet,Poor,1,0,1,0
4,1,0.150747,77,Secondary School,Male,Yes,Never Smoked,Mild Activity,No,Low-Carb Diet,Good,1,1,0,0


In [ ]:
# making sure both columns are the same
(df2['Diabetic'] == df2['Chronic_Diabetes']).value_counts()


,count
True,1000


In [ ]:
#merging the two columns
df2['Diabetic'] = df2[['Diabetic', 'Chronic_Diabetes']].max(axis=1)


In [ ]:
#dropping the chronic diabetes row
df2 = df2.drop(columns=['Chronic_Diabetes'])

In [ ]:
# Renaming diabetic column
df2.rename(columns={'Diabetic': 'Diabetes'}, inplace=True)


In [ ]:
#displaying new dataset 2
df2.head()

,Diabetes,AlcoholLevel,Age,Education_Level,Gender,Family_History,Smoking_Status,Physical_Activity,Depression_Status,Nutrition_Diet,Sleep_Quality,Dementia,Hypertension,CardiovascularDisease
0,1,0.084974,60,Primary School,Female,No,Current Smoker,Sedentary,No,Low-Carb Diet,Poor,0,0,0
1,0,0.016973,61,Secondary School,Male,No,Former Smoker,Moderate Activity,No,Low-Carb Diet,Poor,1,0,1
2,0,0.009000,69,Primary School,Male,Yes,Former Smoker,Moderate Activity,No,Mediterranean Diet,Poor,0,0,1
3,0,0.086437,78,Secondary School,Female,Yes,Never Smoked,Mild Activity,Yes,Balanced Diet,Poor,1,1,0
4,1,0.150747,77,Secondary School,Male,Yes,Never Smoked,Mild Activity,No,Low-Carb Diet,Good,1,0,0


##Sorting Columns Alphabetically

In [ ]:
# print all the data frames to compare and contrast information
#displaying new dataset 1
df1.info()

#displaying new dataset 2
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Age                      2149 non-null   int64  
 1   Gender                   2149 non-null   int64  
 2   EducationLevel           2149 non-null   int64  
 3   Smoking                  2149 non-null   int64  
 4   AlcoholConsumption       2149 non-null   float64
 5   PhysicalActivity         2149 non-null   float64
 6   DietQuality              2149 non-null   float64
 7   SleepQuality             2149 non-null   float64
 8   FamilyHistoryAlzheimers  2149 non-null   int64  
 9   CardiovascularDisease    2149 non-null   int64  
 10  Diabetes                 2149 non-null   int64  
 11  Depression               2149 non-null   int64  
 12  Hypertension             2149 non-null   int64  
 13  Diagnosis                2149 non-null   int64  
dtypes: float64(4), int64(10)

##Cleaning Diet column

In [ ]:
#identify unique values
df2['Nutrition_Diet'].unique()

array(['Low-Carb Diet', 'Mediterranean Diet', 'Balanced Diet'],
      dtype=object)

I am going to classify the mediteranean diet as an 8 because its statistically seen as a very healthy diet.

The Balanced Diet will be given an 7.

And the Low-Carb diet will be given a 6.

This is to allow the diet quality and nutrition_diets to be merged.

This is subjective to debate and I am not a nutritionist, nor do I know the exact rating the other datset used to determine its 1-10 scale rating.

In [ ]:
# Changing Nutrition_Diet to Diet Quality marker
df2['Nutrition_Diet'] = df2['Nutrition_Diet'].replace({
    'Mediterranean Diet': 8,
    'Balanced Diet': 7,
    'Low-Carb Diet': 6
})


/tmp/ipython-input-3923311371.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Nutrition_Diet'] = df2['Nutrition_Diet'].replace({


In [ ]:
# Renaming diet column
df2.rename(columns={'Nutrition_Diet': 'DietQuality'}, inplace=True)


##Current Info

In [ ]:
# print all the data frames to compare and contrast information
#displaying new dataset 1
df1.info()

#displaying new dataset 2
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Age                      2149 non-null   int64  
 1   Gender                   2149 non-null   int64  
 2   EducationLevel           2149 non-null   int64  
 3   Smoking                  2149 non-null   int64  
 4   AlcoholConsumption       2149 non-null   float64
 5   PhysicalActivity         2149 non-null   float64
 6   DietQuality              2149 non-null   float64
 7   SleepQuality             2149 non-null   float64
 8   FamilyHistoryAlzheimers  2149 non-null   int64  
 9   CardiovascularDisease    2149 non-null   int64  
 10  Diabetes                 2149 non-null   int64  
 11  Depression               2149 non-null   int64  
 12  Hypertension             2149 non-null   int64  
 13  Diagnosis                2149 non-null   int64  
dtypes: float64(4), int64(10)

##Cleaning Smoking column

In [ ]:
#Getting possibilities for smoking status
df2['Smoking_Status'].unique()

array(['Current Smoker', 'Former Smoker', 'Never Smoked'], dtype=object)

In [ ]:
# Changing status to if someone has ever smoked in there life to binary output
df2['Smoking_Status'] = df2['Smoking_Status'].replace({
    'Current Smoker': 1,
    'Never Smoked': 0,
    'Former Smoker': 1
})

/tmp/ipython-input-2599142669.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Smoking_Status'] = df2['Smoking_Status'].replace({


In [ ]:
# Renaming smoking column
df2.rename(columns={'Smoking_Status': 'Smoking'}, inplace=True)


##Cleaning gender column

In [ ]:
# Changing male and female column to 1 = female and 0 = male
df2['Gender'] = df2['Gender'].replace({
    'Female': 1,
    'Male': 0
})

/tmp/ipython-input-3862266842.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Gender'] = df2['Gender'].replace({


##Cleaning sleep column

In [ ]:
df2['Sleep_Quality'].unique()

array(['Poor', 'Good'], dtype=object)

In [ ]:
df1['SleepQuality'].unique()

array([9.02567867, 7.15129274, 9.67357416, ..., 5.76946355, 8.32287396,
       9.87871052])

Changing poor sleep to be 4 because that corresponds to the lowest number in the df1, and good sleep to be 8 because that is the hightest number, roughly.

In [ ]:
# Changing sleep status to numeric output
df2['Sleep_Quality'] = df2['Sleep_Quality'].replace({
    'Poor': 4,
    'Good': 8
})

/tmp/ipython-input-4030286583.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Sleep_Quality'] = df2['Sleep_Quality'].replace({


In [ ]:
# Renaming sleep column
df2.rename(columns={'Sleep_Quality': 'SleepQuality'}, inplace=True)


##Cleaning physical activity column

In [ ]:
#identifying unique values
df2['Physical_Activity'].unique()

array(['Sedentary', 'Moderate Activity', 'Mild Activity'], dtype=object)

In [ ]:
df1['PhysicalActivity'].unique()

array([6.32711247, 7.61988454, 7.84498779, ..., 9.88600229, 6.35428175,
       6.57099338])

I have decided to label the various activity levels as such.

In [ ]:
# Changing physical activity status to numeric output
df2['Physical_Activity'] = df2['Physical_Activity'].replace({
    'Sedentary': 1,
    'Mild Activity': 4,
    'Moderate Activity': 6,
    'Active': 9
})

/tmp/ipython-input-4085346684.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Physical_Activity'] = df2['Physical_Activity'].replace({


In [ ]:
# Renaming physical activity column
df2.rename(columns={'Physical_Activity': 'PhysicalActivity'}, inplace=True)


##Cleaning Family History Column

In [ ]:
df2['Family_History'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
# Changing family history status to numeric output
df2['Family_History'] = df2['Family_History'].replace({
    'No': 0,
    'Yes': 1
})

/tmp/ipython-input-1393148501.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Family_History'] = df2['Family_History'].replace({


In [ ]:
# Renaming family history column
df2.rename(columns={'Family_History': 'FamilyHistory'}, inplace=True)


##Cleaning Education column

In [ ]:
df2['Education_Level'].unique()

array(['Primary School', 'Secondary School', 'No School',
       'Diploma/Degree'], dtype=object)

In [ ]:
df1['EducationLevel'].unique()

array([2, 0, 1, 3])

In [ ]:
# Changing physical activity status to numeric output
df2['Education_Level'] = df2['Education_Level'].replace({
    'No School': 0,
    'Primary School': 1,
    'Secondary School': 2,
    'Diploma/Degree': 3
})

/tmp/ipython-input-2478306484.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Education_Level'] = df2['Education_Level'].replace({


In [ ]:
# Renaming Education column
df2.rename(columns={'Education_Level': 'EducationLevel'}, inplace=True)


##Cleaning Depression column

In [ ]:
df2['Depression_Status'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
df1['Depression'].unique()

array([1, 0])

In [ ]:
# Changing depression status to numeric output
df2['Depression_Status'] = df2['Depression_Status'].replace({
    'No': 0,
    'Yes': 1
})

/tmp/ipython-input-2642822626.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Depression_Status'] = df2['Depression_Status'].replace({


In [ ]:
# Renaming depression column
df2.rename(columns={'Depression_Status': 'Depression'}, inplace=True)


##Cleaning alcohol level

In [ ]:
df2['AlcoholLevel'].unique()

array([0.08497363, 0.01697277, 0.00900025, 0.08643726, 0.15074731,
       0.1140278 , 0.01619378, 0.16115808, 0.01575425, 0.09733954,
       0.06748564, 0.08267123, 0.02807717, 0.08805155, 0.15656361,
       0.1659716 , 0.03567131, 0.02930638, 0.15908456, 0.19710716,
       0.09234223, 0.08905676, 0.04706498, 0.0022444 , 0.1559942 ,
       0.1055605 , 0.10967133, 0.05261273, 0.1413211 , 0.14555626,
       0.01621965, 0.06240634, 0.1894373 , 0.16636984, 0.13061763,
       0.15008774, 0.08112397, 0.1656683 , 0.09992415, 0.04157571,
       0.10991138, 0.05445505, 0.14617384, 0.19078454, 0.04034117,
       0.07321483, 0.14017791, 0.0227364 , 0.04778358, 0.08807547,
       0.02556337, 0.18617617, 0.04906598, 0.0979699 , 0.10318646,
       0.10808652, 0.16685116, 0.1303138 , 0.15566145, 0.14444342,
       0.04741042, 0.00132653, 0.17627566, 0.03855862, 0.0289448 ,
       0.05047045, 0.07885336, 0.10065803, 0.12261174, 0.12878761,
       0.14539247, 0.12008087, 0.10553423, 0.1484994 , 0.14102

In [ ]:
df2['AlcoholLevel'].describe()


,AlcoholLevel
count,1000.000000
mean,0.098429
std,0.058715
min,0.000414
25%,0.045505
50%,0.098235
75%,0.151840
max,0.199866


In [ ]:
df1['AlcoholConsumption'].unique()

array([13.29721773,  4.54252382, 19.55508453, ...,  4.59467018,
        8.67450518,  7.89070315])

I am assuming the original scale of this alcohol is units per week being roughly 20 units max per week. I am going to reverse this so it matches with df1 and is easier for interpretation when modelling.

In [ ]:
df2['AlcoholLevel'] = df2['AlcoholLevel'] / 0.2 * 20


In [ ]:
# Renaming alcohol column
df2.rename(columns={'AlcoholLevel': 'AlcoholConsumption'}, inplace=True)


##Renaming some columns in Dataset 1

In [ ]:
# Renaming diagnosis column
df1.rename(columns={'Diagnosis': 'Dementia'}, inplace=True)
# Renaming family history column
df1.rename(columns={'FamilyHistoryAlzheimers': 'FamilyHistory'}, inplace=True)


##Finalizing Cleaning

I am choosing not to remove any rows with columns that have 0 in them because there are many bianry values.

In [ ]:
#Converting floats to integers, fill any NAN values with 0
#df1
df1['AlcoholConsumption'] = df1['AlcoholConsumption'].fillna(0).astype(int)
df1['DietQuality'] = df1['DietQuality'].fillna(0).astype(int)
df1['PhysicalActivity'] = df1['PhysicalActivity'].fillna(0).astype(int)
df1['SleepQuality'] = df1['SleepQuality'].fillna(0).astype(int)
#df2
df2['AlcoholConsumption'] = df2['AlcoholConsumption'].fillna(0).astype(int)

# Preliminary Exploratory Anlysis

In [ ]:
#sorting columns by alphabet ascending order
df1 = df1.reindex(sorted(df1.columns), axis=1)
df2 = df2.reindex(sorted(df2.columns), axis=1)


In [ ]:
# print all the data frames to compare and contrast information
#displaying new dataset 1
df1.info()

#displaying new dataset 2
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    2149 non-null   int64
 1   AlcoholConsumption     2149 non-null   int64
 2   CardiovascularDisease  2149 non-null   int64
 3   Dementia               2149 non-null   int64
 4   Depression             2149 non-null   int64
 5   Diabetes               2149 non-null   int64
 6   DietQuality            2149 non-null   int64
 7   EducationLevel         2149 non-null   int64
 8   FamilyHistory          2149 non-null   int64
 9   Gender                 2149 non-null   int64
 10  Hypertension           2149 non-null   int64
 11  PhysicalActivity       2149 non-null   int64
 12  SleepQuality           2149 non-null   int64
 13  Smoking                2149 non-null   int64
dtypes: int64(14)
memory usage: 235.2 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10

In [ ]:
df1.head(10)

,Age,AlcoholConsumption,CardiovascularDisease,Dementia,Depression,Diabetes,DietQuality,EducationLevel,FamilyHistory,Gender,Hypertension,PhysicalActivity,SleepQuality,Smoking
0,73,13,0,0,1,1,1,2,0,0,0,6,9,0
1,89,4,0,0,0,0,0,0,0,0,0,7,7,0
2,73,19,0,0,0,0,1,1,1,0,0,7,9,0
3,74,12,0,0,0,0,7,1,0,1,0,8,8,1
4,89,18,0,0,0,0,0,0,0,0,0,6,5,0
5,86,4,0,0,0,1,1,1,0,1,0,0,7,0
6,68,0,0,0,0,0,5,2,0,0,0,9,5,1
7,75,13,0,1,0,0,8,1,0,0,0,4,4,0
8,72,12,0,0,0,0,6,0,0,1,1,1,5,0
9,87,16,1,0,0,0,8,0,0,0,0,6,7,1


In [ ]:
df2.head(10)

,Age,AlcoholConsumption,CardiovascularDisease,Dementia,Depression,Diabetes,DietQuality,EducationLevel,FamilyHistory,Gender,Hypertension,PhysicalActivity,SleepQuality,Smoking
0,60,8,0,0,0,1,6,1,0,1,0,1,4,1
1,61,1,1,1,0,0,6,2,0,0,0,6,4,1
2,69,0,1,0,0,0,8,1,1,0,0,6,4,1
3,78,8,0,1,1,0,7,2,1,1,1,4,4,0
4,77,15,0,1,0,1,6,2,1,0,0,4,8,0
5,67,11,0,1,1,1,6,0,0,0,0,4,4,1
6,87,1,0,1,0,1,8,1,0,0,0,4,4,0
7,66,16,0,0,0,0,6,2,0,1,1,4,4,1
8,66,1,0,0,0,0,8,2,0,1,0,4,4,1
9,87,9,0,1,1,1,7,3,0,1,0,1,8,1


##Merging the datasets

In [ ]:
#appending df1 and df2
merged_df = pd.concat([df1, df2], axis=0, ignore_index=True)


In [ ]:
#adding PatientID starting at 0
merged_df['PatientID'] = range(len(merged_df))


In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3149 entries, 0 to 3148
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    3149 non-null   int64
 1   AlcoholConsumption     3149 non-null   int64
 2   CardiovascularDisease  3149 non-null   int64
 3   Dementia               3149 non-null   int64
 4   Depression             3149 non-null   int64
 5   Diabetes               3149 non-null   int64
 6   DietQuality            3149 non-null   int64
 7   EducationLevel         3149 non-null   int64
 8   FamilyHistory          3149 non-null   int64
 9   Gender                 3149 non-null   int64
 10  Hypertension           3149 non-null   int64
 11  PhysicalActivity       3149 non-null   int64
 12  SleepQuality           3149 non-null   int64
 13  Smoking                3149 non-null   int64
 14  PatientID              3149 non-null   int64
dtypes: int64(15)
memory usage: 369.2 KB


In [ ]:
merged_df.head(10)

,Age,AlcoholConsumption,CardiovascularDisease,Dementia,Depression,Diabetes,DietQuality,EducationLevel,FamilyHistory,Gender,Hypertension,PhysicalActivity,SleepQuality,Smoking,PatientID
0,73,13,0,0,1,1,1,2,0,0,0,6,9,0,0
1,89,4,0,0,0,0,0,0,0,0,0,7,7,0,1
2,73,19,0,0,0,0,1,1,1,0,0,7,9,0,2
3,74,12,0,0,0,0,7,1,0,1,0,8,8,1,3
4,89,18,0,0,0,0,0,0,0,0,0,6,5,0,4
5,86,4,0,0,0,1,1,1,0,1,0,0,7,0,5
6,68,0,0,0,0,0,5,2,0,0,0,9,5,1,6
7,75,13,0,1,0,0,8,1,0,0,0,4,4,0,7
8,72,12,0,0,0,0,6,0,0,1,1,1,5,0,8
9,87,16,1,0,0,0,8,0,0,0,0,6,7,1,9


##Saving data frames to csv files

In [ ]:
# Save df1
df1.to_csv('/content/df1_clean.csv', index=False)

# Save df2
df2.to_csv('/content/df2_clean.csv', index=False)

# If you have a merged dataset
merged_df.to_csv('/content/merged_df.csv', index=False)


##Entire merged data frame

In [ ]:
merged_df

,Age,AlcoholConsumption,CardiovascularDisease,Dementia,Depression,Diabetes,DietQuality,EducationLevel,FamilyHistory,Gender,Hypertension,PhysicalActivity,SleepQuality,Smoking,PatientID
0,73,13,0,0,1,1,1,2,0,0,0,6,9,0,0
1,89,4,0,0,0,0,0,0,0,0,0,7,7,0,1
2,73,19,0,0,0,0,1,1,1,0,0,7,9,0,2
3,74,12,0,0,0,0,7,1,0,1,0,8,8,1,3
4,89,18,0,0,0,0,0,0,0,0,0,6,5,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3144,88,8,0,1,0,1,7,3,1,0,0,4,4,0,3144
3145,80,14,0,0,0,1,6,1,0,1,0,6,4,0,3145
3146,67,7,0,0,0,1,7,1,0,1,0,1,8,0,3146
3147,62,3,0,1,1,0,6,0,1,0,0,1,8,0,3147


# Train Test Split

# Training Models

# Going Further

# Conclusion and Discussion